### ISSUE TITLE
Path issue on Linux

### ISSUE THREAD

**Issue by danballance** [jaxter184/bwEdit-Python#4]
Ubuntu 16.04. Python 3.5 and 3.6.

```
> python main.php

Heyo I'm Jaxter, thanks for using my little script. Notice how I said 'my'. That's right, this is something that I made, and you should therefore be pretty careful about using it. I won't take responsibility for breaking your Bitwig devices, so make sure you have a copy of them saved somewhere before starting. Also, be cautious in general; just because I trust my own work doesn't mean you should.
Now, with the fearmongering out of the way, lets get started.

Enter the subdirectory that your devices are in. (If they're in the 'inputs' folder, just press enter)
-NoteEcho.bwdevice
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    magic(file, inputDir)
  File "main.py", line 14, in magic
    device_data = fs.read_binary(directory + '\\' + name)
  File "/home/dan/Code/python/bwConvert/src/lib/fs.py", line 16, in read_binary
    with open(path, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'input\\NoteEcho.bwdevice'
```
Changing line 14 of main.py resolved the issue for me:

```
device_data = fs.read_binary(os.path.join(directory, name))
```

**Comment by jaxter184** [comment]
Replaced the line as suggested
