### ISSUE TITLE
Unpack process doesn't work on Ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by danballance** [jaxter184/bwEdit-Python#6]
Ubuntu 16.04 x64. Python 3.5 and 3.6.

```
[I] (env3.6) dan@dan-UX303UA ~/C/p/bwConvert> python main.py
Heyo I'm Jaxter, thanks for using my little script. Notice how I said 'my'. That's right, this is something that I made, and you should therefore be pretty careful about using it. I won't take responsibility for breaking your Bitwig devices, so make sure you have a copy of them saved somewhere before starting. Also, be cautious in general; just because I trust my own work doesn't mean you should.
Now, with the fearmongering out of the way, lets get started.

Enter the subdirectory that your devices are in. (If they're in the 'inputs' folder, just press enter)
-NoteEcho.bwdevice
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    magic(file, inputDir)
  File "main.py", line 24, in magic
    gather = decoder.bwDecode(device_data)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 417, in bwDecode
    output.append(getClass(text))
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 282, in getClass
    getParams(text, object)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 249, in getParams
    value = parseField(text)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 139, in parseField
    tempList.append(getClass(text))
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 282, in getClass
    getParams(text, object)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 249, in getParams
    value = parseField(text)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 108, in parseField
    return getClass(text)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 282, in getClass
    getParams(text, object)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 249, in getParams
    value = parseField(text)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 108, in parseField
    return getClass(text)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 282, in getClass
    getParams(text, object)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 249, in getParams
    value = parseField(text)
  File "/home/dan/Code/python/bwConvert/src/decoder.py", line 168, in parseField
    flVals.append(struct.unpack('f', struct.pack('L', intConv(text[offset:offset + 4])))[0])
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by jaxter184** [comment]
should work now, if someone could test it, that'd be great
